poll_repositories_for_changes:
  every:
    - "10m"
    - :first_in: "5s"
  class: "PollRepositoriesJob"
  queue: low
  args:
  description: "Fetches any missed changes from added repositories"

enforce_timeouts_on_attempts:
  every:
    - "5m"
    - :first_in: "5m"
  class: "EnforceTimeoutsJob"
  queue: low
  args:
  description: "Errors any attempts where the workers should have timed out"
